### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by skipit** [skipit/SimpleToDoList#1]
my app is complete, please review. /cc @codepathreview @codepath

Please let me know if anything else is expected. 
Will work on the Extensions.

**Comment by nesquena** [comment]
What's your full name so I can match you?

**Comment by skipit** [comment]
Shanta Pavan Namburi

**Comment by nesquena** [comment]
Thank you Shanta. Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a personalized code review for each submitted project once the bootcamp starts.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 5-10 minute phone conversation** [here](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU). Navigate to [January 19th and dates onward](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Please make sure to **include the best number** to reach you at in the scheduled event? Look forward to chatting soon!

**Comment by skipit** [comment]
Hi Nathan, Updated the Project  to support Database.  /cc @codepathreview @codepath

Also uses custom Adapter. Please let me know if you want me to update the display style ? and what exactly to change in the Custom Adapter.

**Comment by nesquena** [comment]
Yep, both the custom adapter and the SQLiteOpenHelper look good. As a final step, I'd like to see you either priority or due date or similar to the todo items and let the user choose that (and edit that). Add the additional data to the list item in addition to the body.

**Comment by skipit** [comment]
Hi Nathan, Do you think I can attend this time in South Bay ? /cc @codepathreview @codepath
